language: python
python: "2.7"
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c buildout.cfg
  - bin/buildout -N -t 3 -c buildout.cfg
  - pip install coveralls
script: bin/coverage
after_success:
  coveralls
